const SET_CART = "SET_CART"
const ADD_TO_CART = "ADD_TO_CART"
const INCREMENT_ITEM = "INCREMENT_ITEM"
const DECREMENT_ITEM = "DECREMENT_ITEM"

export { SET_CART, ADD_TO_CART, INCREMENT_ITEM, DECREMENT_ITEM }
